[package]
name = "yowsl"
version = "0.1.0"
authors = ["Yoshito Komatsu <ykomatsu@akaumigame.org>"]
description = "Yet another Windows Subsystem for Linux tweaker"
license = "Apache-2.0"

[dependencies]
bitflags = "1.0.1"
clap = "2.27.1"
libloading = "0.4.2"
