[package]
name = "yowsl"
version = "0.1.0"
authors = ["Yoshito Komatsu <ykomatsu@akaumigame.org>"]
description = "Yet another Windows Subsystem for Linux tweaker"
license = "Apache-2.0"

[dependencies]
clap = "2.27.1"
lazy_static = "0.2.10"
libloading = "0.4.2"
